services:
  postgres-master:
    image: "postgres:16.1"
    container_name: postgres-master
    environment:
      POSTGRES_DB: "hotels"
      POSTGRES_USER: "hotels"
      POSTGRES_PASSWORD: "123"
    ports:
     - "8000:5432"
    volumes:
      - ./migrations/1-set-wal-level.sql:/docker-entrypoint-initdb.d/1-set-wal-level.sql
      - ./migrations/2-create-tables.sql:/docker-entrypoint-initdb.d/2-create-tables.sql
      - ./migrations/master/initdb/3-create-replication-user.sql:/docker-entrypoint-initdb.d/3-create-replication-user.sql
      - ./migrations/master/initdb/4-create-publication-rok.sql:/docker-entrypoint-initdb.d/4-create-publication-rok.sql
      - ./volumes/master:/var/lib/postgresql/data
  postgres-slave-1:
    image: "postgres:16.1"
    container_name: postgres-slave-1
    depends_on:
      - postgres-master
    environment:
      POSTGRES_DB: "hotels"
      POSTGRES_USER: "hotels"
      POSTGRES_PASSWORD: "123"
    ports:
     - "8001:5432"
    volumes:
      - ./migrations/1-set-wal-level.sql:/docker-entrypoint-initdb.d/1-set-wal-level.sql
      - ./migrations/2-create-tables.sql:/docker-entrypoint-initdb.d/2-create-tables.sql
      - ./migrations/slaves/3-create-replication-user.sql:/docker-entrypoint-initdb.d/3-create-replication-user.sql
      - ./migrations/slaves/slave-1/initdb/4-create-publication-rkd-slave-1.sql:/docker-entrypoint-initdb.d/4-create-publication-rkd-slave-1.sql
      - ./volumes/slave-1:/var/lib/postgresql/data
  postgres-slave-2:
    image: "postgres:16.1"
    container_name: postgres-slave-2
    depends_on:
      - postgres-master
    environment:
      POSTGRES_DB: "hotels"
      POSTGRES_USER: "hotels"
      POSTGRES_PASSWORD: "123"
    ports:
     - "8002:5432"
    volumes:
      - ./migrations/1-set-wal-level.sql:/docker-entrypoint-initdb.d/1-set-wal-level.sql
      - ./migrations/2-create-tables.sql:/docker-entrypoint-initdb.d/2-create-tables.sql
      - ./migrations/slaves/3-create-replication-user.sql:/docker-entrypoint-initdb.d/3-create-replication-user.sql
      - ./migrations/slaves/slave-2/initdb/4-create-publication-rkd-slave-2.sql:/docker-entrypoint-initdb.d/4-create-publication-rkd-slave-2.sql
      - ./volumes/slave-2:/var/lib/postgresql/data
